# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joseph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneSyn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.CharField(max_length=150)),
                ('synonyms', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
