# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joseph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='references',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('file_num', models.CharField(max_length=100)),
            ],
        ),
    ]
