# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joseph', '0002_references'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=2)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Both', 'Both'), ('', 'SELECT')], max_length=6)),
                ('gene', models.CharField(max_length=100)),
                ('aas', models.CharField(max_length=100)),
                ('stage', models.CharField(choices=[('Stage I', 'Stage I'), ('Stage II', 'Stage II'), ('Stage III', 'Stage III'), ('Stage IV', 'Stage IV'), ('Stage X', 'Stage X'), ('Stage IA', 'Stage IA'), ('Stage IIA', 'Stage IIA'), ('Stage IIIA', 'Stage IIIA'), ('Stage IVA', 'Stage IVA'), ('Stage IB', 'Stage IB'), ('Stage IIB', 'Stage IIB'), ('Stage IIIB', 'Stage IIIB'), ('Stage IVB', 'Stage IVB'), ('Stage IC', 'Stage IC'), ('Stage IIC', 'Stage IIC'), ('Stage IIIC', 'Stage IIIC'), ('Stage IVC', 'Stage IVC'), ('', 'SELECT')], max_length=10)),
                ('grade', models.CharField(choices=[('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade I', 'Grade I'), ('Grade II', 'Grade II'), ('Grade III', 'Grade III'), ('Grade IV', 'Grade IV'), ('', 'SELECT')], max_length=10)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='references',
            name='word',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='words',
            name='word',
            field=models.CharField(max_length=150),
        ),
    ]
