# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joseph', '0002_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='references',
            name='word',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='words',
            name='word',
            field=models.CharField(max_length=150),
        ),
    ]
