# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joseph', '0003_auto_20160708_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligibility', models.BooleanField(choices=[(True, 'YES'), (False, 'NO')])),
                ('character', models.CharField(choices=[('disease', 'disease'), ('age', 'age'), ('gender', 'gender'), ('stage', 'stage'), ('grade', 'grade'), ('gene', 'gene'), ('mutation', 'mutation'), ('', 'SELECT')], max_length=30)),
                ('section', models.CharField(choices=[('Title', 'Title'), ('Purpose', 'Purpose'), ('Description', 'Description'), ('Inclusion Criteria', 'Inclusion Criteria'), ('Exclusion Criteria', 'Exclusion Criteria'), ('', 'SELECT')], max_length=10)),
                ('sentence', models.TextField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
