# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joseph', '0003_auto_20160629_1127'),
    ]

    operations = [
    ]
