# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joseph', '0004_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='character',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='section',
        ),
        migrations.AddField(
            model_name='answer',
            name='character',
            field=models.ManyToManyField(to='joseph.Characters'),
        ),
        migrations.AddField(
            model_name='answer',
            name='section',
            field=models.ManyToManyField(to='joseph.Sections'),
        ),
    ]
