# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 17:57
from __future__ import unicode_literals

from django.db import migrations

def load_stores_from_sql():

    import os
    sql_statements = open('C:/Users/310246089/Documents/clinicaltrials_new/joseph/sql/words.sqlite3.sql', 'rb').read().decode('utf-8')
    return sql_statements

class Migration(migrations.Migration):

    dependencies = [
        ('joseph', '0004_auto_20160629_1357'),
    ]

    operations = [
        migrations.RunSQL(load_stores_from_sql()),
    ]
