# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 17:57
from __future__ import unicode_literals

from django.db import migrations

import os

def load_stores_from_sql():


    settings_dir = os.path.dirname(__file__)
    PROJECT_ROOT = os.path.abspath(os.path.dirname(settings_dir))
    SQL_FOLDER = os.path.join(PROJECT_ROOT, 'sql/')
    
    sql_statements = open(SQL_FOLDER+'words.sqlite3.sql', 'rb').read().decode('utf-8')
    return sql_statements

class Migration(migrations.Migration):

    dependencies = [
        ('joseph', '0004_auto_20160629_1357'),
    ]

    operations = [
        migrations.RunSQL(load_stores_from_sql()),
    ]
